#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Jul  8 17:20:28 2019

@author: cheng
"""

chmod +x ./src/*
chmod +x ./mnist_vae_flex/src/*

#VAES-----------------------------------------------------------------------------
#TRAINING: single
python ./src/execute_settingI.py --file-name './mnist_vae_flex/src/main.py' --submit-mode 'qsub' --grid "'5'" "'10'" "'15'" "'20'" "'40'" "'60'" "'80'" "'100'"  #train network
python ./src/execute_settingI.py --file-name './generative_model_collections/main.py' --submit-mode 'qsub' --gan_type VAE CVAE BEGAN --epoch 25 --dataset mnist fashion-mnist --grid "'5'" "'10'" "'15'" "'20'" "'40'" "'60'" "'80'" "'100'"  #train network
python ./src/execute_settingI.py --file-name './generative_model_collections/main_DCGAN.py' --submit-mode 'qsub' --gan_type DCGAN --epoch 25 --dataset celebA --grid "'5'" "'10'" "'15'" "'20'" "'40'" "'60'" "'80'" "'100'"  #train network

#TRAINING: joined
python ./src/execute_settingI.py --file-name './mnist_vae_flex/src/main.py' --submit-mode 'qsub'
python ./src/execute_settingI.py --file-name './generative_model_collections/main.py' --submit-mode 'qsub' --gan_type VAE CVAE BEGAN --epoch 25 --dataset mnist fashion-mnist --grid "'5 10 20 40 60 100'"  #train network
python ./src/execute_settingI.py --file-name './generative_model_collections/main_DCGAN.py' --submit-mode 'qsub' --gan_type DCGAN --epoch 25 --dataset celebA --grid  "'5 10 20 40 60 100'"  #train network


#vaeflex with grid 5 10 20 40 60 80 100
python ./src/execute_setting.py --submit-mode qsub --model-types 'vae-flex' --init-mode "previous-and-random"  --n-z -1 --num-measurements 10 25 50 100 200 300 400 500 600 750  --n-z -1 --pretrained-model-dir './mnist_vae_flex/models/mnist-vae-flex-5-10-15-20-40-60-80-100' --grid "'5 10 15 20 40 60 80 100'" --qsub-time 200000 --measurement-type gaussian --reproducible reproducible --noise-std 0.0 0.5 1 --strict-checking nonstrict --tolerance-checking non-squared
python ./src/execute_setting.py --submit-mode qsub --model-types 'vae-flex' --init-mode "previous-and-random"  --n-z -1 --num-measurements 10 25 50 100 200 300 400 500 600 750  --n-z -1 --pretrained-model-dir './mnist_vae_flex/models/mnist-vae-flex-5-10-15-20-40-60-80-100' --grid "'5 10 15 20 40 60 80 100'" --qsub-time 200000 --measurement-type gaussian --reproducible load_standard --noise-std 0.0 --strict-checking nonstrict strict --tolerance-checking squared --eps 3.85 --input-type random-test --input-seed 2019
python ./src/execute_setting.py --submit-mode qsub --model-types 'vae-flex' --init-mode "previous-and-random"  --n-z -1 --num-measurements 10 25 50 100 200 300 400 500 600 750  --n-z -1 --pretrained-model-dir './mnist_vae_flex/models/mnist-vae-flex-5-10-15-20-40-60-80-100' --grid "'5 10 15 20 40 60 80 100'" --qsub-time 50000 --measurement-type gaussian --reproducible reproducible --flex-chosen '5' '10' '15' '20' '40' '50' '80' '100' --noise-std 0.0 0.1 0.5
#fashion
python ./src/execute_setting.py --submit-mode qsub --model-types 'VAE-flex' --init-mode "previous-and-random"  --n-z -1 --num-measurements 10 25 50 100 200 300 400 500 600 750  --n-z -1 --pretrained-model-dir './generative_model_collections/checkpoint/' --grid "'5 10 20 40 60 100'" --qsub-time 50000 --measurement-type gaussian --reproducible reproducible --noise-std 0.0 0.5 1 --dataset fashion-mnist --tolerance-checking 'squared' --strict-checking strict --eps 0.008

#vaeflex fixed dimension project
python ./src/execute_setting.py --tol 1 --submit-mode qsub --model-types vae-flex --pretrained-model-dir './mnist_vae_flex/models/' --init-mode "previous-and-random" --grid "'5 10 15 20 40 60 80 100'" --measurement-type project --flex-chosen 5 10 20 40 60 80 100 --num-measurements 784 --qsub-time 200000 --input-type
#Vaeflex fixed dimension gaussian
python ./src/execute_setting.py --tol 1 --submit-mode qsub --model-types vae-flex --pretrained-model-dir './mnist_vae_flex/models/' --init-mode "previous-and-random" --grid "'5 10 15 20 40 60 80 100'" --measurement-type gaussian --reproducible reproducible --flex-chosen 5 10 20 40 100 --num-measurements 10 25 50 100 200 750 --qsub-time 200000 --noise-std 0.0 0.5 1
#fashion
python ./src/execute_setting.py --tol 1 --submit-mode qsub --model-types 'VAE-flex' --pretrained-model-dir './generative_model_collections/checkpoint/' --init-mode "previous-and-random" --grid "'5 10 20 40 60 100'" --measurement-type gaussian --reproducible reproducible --flex-chosen 5 10 20 40 100 --num-measurements 10 25 50 100 200 750 --qsub-time 200000 --dataset fashion-mnist --tolerance-checking 'squared' --strict-checking strict --eps 0.005
python ./src/execute_setting.py --tol 1 --submit-mode qsub --model-types 'VAE-flex' --pretrained-model-dir './generative_model_collections/checkpoint/' --init-mode "previous-and-random" --grid "'5 10 20 40 60 100'" --measurement-type project --flex-chosen 5 10 20 40 100 --num-measurements 784 --qsub-time 200000 --dataset fashion-mnist

#VAEALT: choosing seperately trained vaes
python ./src/execute_setting.py --submit-mode qsub --model-types 'vae-flex-alt' --init-mode "previous-and-random"  --n-z -1 --num-measurements 10 25 50 100 200 300 400 500 600 750  --n-z -1 --pretrained-model-dir './mnist_vae_flex/models/' --grid "'5 10 15 20 40 60 80 100'" --qsub-time 50000 --measurement-type gaussian --reproducible reproducible --noise-std 0.0 0.1 0.5

python ./src/execute_setting.py --submit-mode qsub --model-types 'VAE-flex-alt' --init-mode "previous-and-random"  --n-z -1 --num-measurements 10 25 50 100 200 300 400 500 600 750  --n-z -1 --pretrained-model-dir './generative_model_collections/checkpoint/' --grid "'5 10 20 40 60'" --qsub-time 50000 --measurement-type gaussian --reproducible reproducible --noise-std 0.0 0.5 1 --dataset fashion-mnist --tolerance-checking 'squared' --strict-checking strict --eps 0.008

#Independently trained
python ./src/execute_setting.py --submit-mode qsub --model-types 'vae-flex' --init-mode "previous-and-random"  --grid "'5'" --flex-chosen 5 --num-measurements 10 25 50 100 200 300 400 500 600 750 --pretrained-model-dir './mnist_vae/models/' --qsub-time 50000 --measurement-type gaussian --reproducible reproducible --noise-std 0.0 --tol 1 --input-type random-test full-input --input-seed 2019
python ./src/execute_setting.py --submit-mode qsub --model-types 'vae-flex' --init-mode "previous-and-random"  --grid "'10'" --flex-chosen 10 --num-measurements 10 25 50 100 200 300 400 500 600 750 --pretrained-model-dir './mnist_vae/models/' --qsub-time 50000 --measurement-type gaussian --reproducible reproducible --noise-std 0.0 --tol 1 --input-type random-test full-input --input-seed 2019
python ./src/execute_setting.py --submit-mode qsub --model-types 'vae-flex' --init-mode "previous-and-random"  --grid "'15'" --flex-chosen 15 --num-measurements 10 25 50 100 200 300 400 500 600 750 --pretrained-model-dir './mnist_vae/models/' --qsub-time 50000 --measurement-type gaussian --reproducible reproducible --noise-std 0.0 --tol 1 --input-type random-test full-input --input-seed 2019
python ./src/execute_setting.py --submit-mode qsub --model-types 'vae-flex' --init-mode "previous-and-random"  --grid "'20'" --flex-chosen 20 --num-measurements 10 25 50 100 200 300 400 500 600 750 --pretrained-model-dir './mnist_vae/models/' --qsub-time 50000 --measurement-type gaussian --reproducible reproducible --noise-std 0.0 --tol 1 --input-type random-test full-input --input-seed 2019
python ./src/execute_setting.py --submit-mode qsub --model-types 'vae-flex' --init-mode "previous-and-random"  --grid "'40'" --flex-chosen 40 --num-measurements 10 25 50 100 200 300 400 500 600 750 --pretrained-model-dir './mnist_vae/models/' --qsub-time 50000 --measurement-type gaussian --reproducible reproducible --noise-std 0.0 --tol 1 --input-type random-test full-input --input-seed 2019
python ./src/execute_setting.py --submit-mode qsub --model-types 'vae-flex' --init-mode "previous-and-random"  --grid "'60'" --flex-chosen 60 --num-measurements 10 25 50 100 200 300 400 500 600 750 --pretrained-model-dir './mnist_vae/models/' --qsub-time 50000 --measurement-type gaussian --reproducible reproducible --noise-std 0.0 --tol 1 --input-type random-test full-input --input-seed 2019
python ./src/execute_setting.py --submit-mode qsub --model-types 'vae-flex' --init-mode "previous-and-random"  --grid "'80'" --flex-chosen 80 --num-measurements 10 25 50 100 200 300 400 500 600 750 --pretrained-model-dir './mnist_vae/models/' --qsub-time 50000 --measurement-type gaussian --reproducible reproducible --noise-std 0.0 --tol 1 --input-type random-test full-input --input-seed 2019
python ./src/execute_setting.py --submit-mode qsub --model-types 'vae-flex' --init-mode "previous-and-random"  --grid "'100'" --flex-chosen 100 --num-measurements 10 25 50 100 200 300 400 500 600 750 --pretrained-model-dir './mnist_vae/models/' --qsub-time 50000 --measurement-type gaussian --reproducible reproducible --noise-std 0.0 --tol 1 --input-type random-test full-input --input-seed 2019

python ./src/execute_setting.py --submit-mode qsub --model-types 'VAE-fixed' --init-mode "previous-and-random"  --grid "'5'" --flex-chosen 5 --num-measurements 10 25 50 100 200 300 400 500 600 750 --pretrained-model-dir './generative_model_collections/checkpoint/' --measurement-type gaussian --reproducible reproducible --noise-std 0.0 0.5 1 --tol 1 --dataset fashion-mnist --input-type full-input random-test --qsub-time 300000
python ./src/execute_setting.py --submit-mode qsub --model-types 'VAE-fixed' --init-mode "previous-and-random"  --grid "'10'" --flex-chosen 10 --num-measurements 10 25 50 100 200 300 400 500 600 750 --pretrained-model-dir './generative_model_collections/checkpoint/' --measurement-type gaussian --reproducible reproducible --noise-std 0.0 0.5 1 --tol 1 --dataset fashion-mnist --input-type full-input random-test --qsub-time 300000
python ./src/execute_setting.py --submit-mode qsub --model-types 'VAE-fixed' --init-mode "previous-and-random"  --grid "'20'" --flex-chosen 20 --num-measurements 10 25 50 100 200 300 400 500 600 750 --pretrained-model-dir './generative_model_collections/checkpoint/' --measurement-type gaussian --reproducible reproducible --noise-std 0.0 0.5 1 --tol 1 --dataset fashion-mnist --input-type full-input random-test --qsub-time 300000
python ./src/execute_setting.py --submit-mode qsub --model-types 'VAE-fixed' --init-mode "previous-and-random"  --grid "'40'" --flex-chosen 40 --num-measurements 10 25 50 100 200 300 400 500 600 750 --pretrained-model-dir './generative_model_collections/checkpoint/' --measurement-type gaussian --reproducible reproducible --noise-std 0.0 0.5 1 --tol 1 --dataset fashion-mnist --input-type full-input random-test --qsub-time 300000
python ./src/execute_setting.py --submit-mode qsub --model-types 'VAE-fixed' --init-mode "previous-and-random"  --grid "'60'" --flex-chosen 60 --num-measurements 10 25 50 100 200 300 400 500 600 750 --pretrained-model-dir './generative_model_collections/checkpoint/' --measurement-type gaussian --reproducible reproducible --noise-std 0.0 0.5 1 --tol 1 --dataset fashion-mnist --input-type full-input random-test --qsub-time 300000

#Wavelet-----------------------------------------------------------------------
#Wavelet ONB, subparts (incomplete)
#Gaussian measurements NOT IMPLEMENTED NOW
python ./src/execute_setting.py --submit-mode qsub --model-types lasso-wavelet --init-mode "previous-and-random"  --num-measurements 10 25 50 100 200 300 400 500 600 750  --n-z -1 --tv-or-lasso-mode cvxpy-constrEq-reweight1-synthesis-nonredundant-28 --reproducible reproducible --measurement-type gaussian --kterm 5 10 20 40 60 80 100 125 150 175 200 250 275 300 325 350 400 450 500 550 600 650 700 750 784 799  --noise-std 0.0 0.1 0.5
#Projection
python ./src/execute_setting.py --submit-mode qsub --model-types lasso-wavelet --init-mode "previous-and-random"   --n-z -1 --tv-or-lasso-mode bestkTermApprox-constrEq-reweight1-synthesis-nonredundant-28 --reproducible reproducible --measurement-type project --kterm 5 10 20 40 60 80 100 125 150 175 200 250 275 300 325 350 400 450 500 550 600 650 700 750 784 799

python ./src/execute_setting.py --submit-mode qsub --model-types lasso-wavelet --init-mode "previous-and-random"  --num-measurements 10 25 50 100 200 300 400 500 600 750  --n-z -1 --tv-or-lasso-mode cvxpy-constrEq-reweight1-synthesis-nonredundant-28 --reproducible reproducible --measurement-type gaussian --wavelet-type 'db1' 'db2' 'db3' 'db1selected'  --noise-std 0.0

#PCA with/without variance normalization and different levels of used PCA components (fractions: 1,0.5,0.1,0.05,0.01)
python ./src/execute_setting.py --submit-mode qsub --model-types lasso-pca --init-mode "previous-and-random"  --num-measurements 10 25 50 100 200 300 400 500 600 750 --n-z -1 --tv-or-lasso-mode cvxpy-constrEq-reweight1-synthesis-unnormalized-own-pcafraction0.01-affine --reproducible reproducible --measurement-type gaussian --noise-std 0.0 0.1 0.5
python ./src/execute_setting.py --submit-mode qsub --model-types lasso-pca --init-mode "previous-and-random"  --num-measurements 10 25 50 100 200 300 400 500 600 750 --n-z -1 --tv-or-lasso-mode cvxpy-constrEq-reweight1-synthesis-unnormalized-own-pcafraction0.05-affine --reproducible reproducible --measurement-type gaussian --noise-std 0.0 0.1 0.5
python ./src/execute_setting.py --submit-mode qsub --model-types lasso-pca --init-mode "previous-and-random"  --num-measurements 10 25 50 100 200 300 400 500 600 750 --n-z -1 --tv-or-lasso-mode cvxpy-constrEq-reweight1-synthesis-unnormalized-own-pcafraction0.1-affine --reproducible reproducible --measurement-type gaussian --noise-std 0.0 0.1 0.5
python ./src/execute_setting.py --submit-mode qsub --model-types lasso-pca --init-mode "previous-and-random"  --num-measurements 10 25 50 100 200 300 400 500 600 750 --n-z -1 --tv-or-lasso-mode cvxpy-constrEq-reweight1-synthesis-unnormalized-own-pcafraction0.5-affine --reproducible reproducible --measurement-type gaussian --noise-std 0.0 0.1 0.5
python ./src/execute_setting.py --submit-mode qsub --model-types lasso-pca --init-mode "previous-and-random"  --num-measurements 10 25 50 100 200 300 400 500 600 750 --n-z -1 --tv-or-lasso-mode cvxpy-constrEq-reweight1-synthesis-unnormalized-own-pcafraction1-affine --reproducible reproducible --measurement-type gaussian --noise-std 0.0 0.1 0.5
python ./src/execute_setting.py --submit-mode qsub --model-types lasso-pca --init-mode "previous-and-random"  --num-measurements 10 25 50 100 200 300 400 500 600 750 --n-z -1 --tv-or-lasso-mode cvxpy-constrEq-reweight1-synthesis-normalized-own-pcafraction0.01-affine --reproducible reproducible --measurement-type gaussian --noise-std 0.0 0.1 0.5
python ./src/execute_setting.py --submit-mode qsub --model-types lasso-pca --init-mode "previous-and-random"  --num-measurements 10 25 50 100 200 300 400 500 600 750 --n-z -1 --tv-or-lasso-mode cvxpy-constrEq-reweight1-synthesis-normalized-own-pcafraction0.05-affine --reproducible reproducible --measurement-type gaussian --noise-std 0.0 0.1 0.5
python ./src/execute_setting.py --submit-mode qsub --model-types lasso-pca --init-mode "previous-and-random"  --num-measurements 10 25 50 100 200 300 400 500 600 750 --n-z -1 --tv-or-lasso-mode cvxpy-constrEq-reweight1-synthesis-normalized-own-pcafraction0.1-affine --reproducible reproducible --measurement-type gaussian --noise-std 0.0 0.1 0.5
python ./src/execute_setting.py --submit-mode qsub --model-types lasso-pca --init-mode "previous-and-random"  --num-measurements 10 25 50 100 200 300 400 500 600 750 --n-z -1 --tv-or-lasso-mode cvxpy-constrEq-reweight1-synthesis-normalized-own-pcafraction0.5-affine --reproducible reproducible --measurement-type gaussian --noise-std 0.0 0.1 0.5
python ./src/execute_setting.py --submit-mode qsub --model-types lasso-pca --init-mode "previous-and-random"  --num-measurements 10 25 50 100 200 300 400 500 600 750 --n-z -1 --tv-or-lasso-mode cvxpy-constrEq-reweight1-synthesis-normalized-own-pcafraction1-affine --reproducible reproducible --measurement-type gaussian --noise-std 0.0 0.1 0.5
#raw
python ./src/execute_setting.py --submit-mode qsub --model-types lasso-pca --init-mode "previous-and-random"  --num-measurements 10 25 50 100 200 300 400 500 600 750 --n-z -1 --tv-or-lasso-mode cvxpy-constrEq-reweight1-synthesis-unnormalized-rawDict-pcafraction0.01-affine --reproducible reproducible --measurement-type gaussian --noise-std 0.0 0.1 0.5
python ./src/execute_setting.py --submit-mode qsub --model-types lasso-pca --init-mode "previous-and-random"  --num-measurements 10 25 50 100 200 300 400 500 600 750 --n-z -1 --tv-or-lasso-mode cvxpy-constrEq-reweight1-synthesis-unnormalized-rawDict-pcafraction1-affine --reproducible reproducible --measurement-type gaussian --noise-std 0.0 0.1 0.5
#Dict
python ./src/execute_setting.py --submit-mode qsub --model-types lasso-pca --init-mode "previous-and-random"  --num-measurements 10 25 50 100 200 300 400 500 600 750 --n-z -1 --tv-or-lasso-mode cvxpy-constrEq-reweight1-synthesis-normalized-sklearnDictionaryLearning-pcafraction1-affine --reproducible reproducible --measurement-type gaussian --noise-std 0.0 0.1 0.5
python ./src/execute_setting.py --submit-mode qsub --model-types lasso-pca --init-mode "previous-and-random"  --num-measurements 10 25 50 100 200 300 400 500 600 750 --n-z -1 --tv-or-lasso-mode cvxpy-constrEq-reweight1-synthesis-normalized-sklearnDictionaryLearning10-pcafraction1-affine --reproducible reproducible --measurement-type gaussian --noise-std 0.0 0.1 0.5
python ./src/execute_setting.py --submit-mode qsub --model-types lasso-pca --init-mode "previous-and-random"  --num-measurements 10 25 50 100 200 300 400 500 600 750 --n-z -1 --tv-or-lasso-mode cvxpy-constrEq-reweight1-synthesis-normalized-sklearnDictionaryLearning25-pcafraction1-affine --reproducible reproducible --measurement-type gaussian --noise-std 0.0 0.1 0.5
python ./src/execute_setting.py --submit-mode qsub --model-types lasso-pca --init-mode "previous-and-random"  --num-measurements 10 25 50 100 200 300 400 500 600 750 --n-z -1 --tv-or-lasso-mode cvxpy-constrEq-reweight1-synthesis-normalized-sklearnDictionaryLearning50-pcafraction1-affine --reproducible reproducible --measurement-type gaussian --noise-std 0.0 0.1 0.5
python ./src/execute_setting.py --submit-mode qsub --model-types lasso-pca --init-mode "previous-and-random"  --num-measurements 10 25 50 100 200 300 400 500 600 750 --n-z -1 --tv-or-lasso-mode cvxpy-constrEq-reweight1-synthesis-normalized-sklearnDictionaryLearning100-pcafraction1-affine --reproducible reproducible --measurement-type gaussian --noise-std 0.0 0.1 0.5
python ./src/execute_setting.py --submit-mode qsub --model-types lasso-pca --init-mode "previous-and-random"  --num-measurements 10 25 50 100 200 300 400 500 600 750 --n-z -1 --tv-or-lasso-mode cvxpy-constrEq-reweight1-synthesis-normalized-sklearnDictionaryLearning200-pcafraction1-affine --reproducible reproducible --measurement-type gaussian --noise-std 0.0 0.1 0.5
python ./src/execute_setting.py --submit-mode qsub --model-types lasso-pca --init-mode "previous-and-random"  --num-measurements 10 25 50 100 200 300 400 500 600 750 --n-z -1 --tv-or-lasso-mode cvxpy-constrEq-reweight1-synthesis-normalized-sklearnDictionaryLearning300-pcafraction1-affine --reproducible reproducible --measurement-type gaussian --noise-std 0.0 0.1 0.5
#DictPartial
python ./src/execute_setting.py --submit-mode qsub --model-types lasso-pca --init-mode "previous-and-random"  --num-measurements 10 25 50 100 200 300 400 500 600 750 --n-z -1 --tv-or-lasso-mode cvxpy-constrEq-reweight1-synthesis-normalized-sklearnDictionaryLearning10-samples55000-pcafraction1-affine --reproducible reproducible --measurement-type gaussian --noise-std 0.0 0.1 0.5
python ./src/execute_setting.py --submit-mode qsub --model-types lasso-pca --init-mode "previous-and-random"  --num-measurements 10 25 50 100 200 300 400 500 600 750 --n-z -1 --tv-or-lasso-mode cvxpy-constrEq-reweight1-synthesis-normalized-sklearnDictionaryLearning25-samples55000-pcafraction1-affine --reproducible reproducible --measurement-type gaussian --noise-std 0.0 0.1 0.5
python ./src/execute_setting.py --submit-mode qsub --model-types lasso-pca --init-mode "previous-and-random"  --num-measurements 10 25 50 100 200 300 400 500 600 750 --n-z -1 --tv-or-lasso-mode cvxpy-constrEq-reweight1-synthesis-normalized-sklearnDictionaryLearning50-samples1000-pcafraction1-affine --reproducible reproducible --measurement-type gaussian --noise-std 0.0 0.1 0.5
python ./src/execute_setting.py --submit-mode qsub --model-types lasso-pca --init-mode "previous-and-random"  --num-measurements 10 25 50 100 200 300 400 500 600 750 --n-z -1 --tv-or-lasso-mode cvxpy-constrEq-reweight1-synthesis-normalized-sklearnDictionaryLearning100-samples1000-pcafraction1-affine --reproducible reproducible --measurement-type gaussian --noise-std 0.0 0.1 0.5
python ./src/execute_setting.py --submit-mode qsub --model-types lasso-pca --init-mode "previous-and-random"  --num-measurements 10 25 50 100 200 300 400 500 600 750 --n-z -1 --tv-or-lasso-mode cvxpy-constrEq-reweight1-synthesis-normalized-sklearnDictionaryLearning200-samples1000-pcafraction1-affine --reproducible reproducible --measurement-type gaussian --noise-std 0.0 0.1 0.5
python ./src/execute_setting.py --submit-mode qsub --model-types lasso-pca --init-mode "previous-and-random"  --num-measurements 10 25 50 100 200 300 400 500 600 750 --n-z -1 --tv-or-lasso-mode cvxpy-constrEq-reweight1-synthesis-normalized-sklearnDictionaryLearning300-samples1000-pcafraction1-affine --reproducible reproducible --measurement-type gaussian --noise-std 0.0 0.1 0.5
#DictCreation
python ./src/execute_settingI.py --training-size 55000 --file-name './src/pca_compute.py' --submit-mode qsub --normalization normalized --mode sklearnDictionaryLearning10 sklearnDictionaryLearning25 sklearnDictionaryLearning50 sklearnDictionaryLearning100 sklearnDictionaryLearning200 sklearnDictionaryLearning300
#Best fitting image
python ./src/execute_setting.py --submit-mode qsub --model-types dict --init-mode "previous-and-random"  --num-measurements 10 25 50 100 200 300 400 500 600 750 --n-z -1 --tv-or-lasso-mode bruteForce-unnormalized-synthesis-kterm1-rawDict --reproducible reproducible --measurement-type gaussian --noise-std 0.0 0.1 0.5

#Lasso
python ./src/execute_setting.py --submit-mode qsub --model-types lasso --init-mode "previous-and-random"  --num-measurements 10 25 50 100 200 300 400 500 600 750 --n-z -1 --tv-or-lasso-mode sklearn --reproducible reproducible --measurement-type gaussian --noise-std 0.0 0.1 0.5 --lmbd 0.1 --dataset mnist fashion-mnist


#TV Norm
python ./src/execute_setting.py --submit-mode qsub --model-types tv-norm --init-mode "previous-and-random"  --num-measurements 10 25 50 100 200 300 400 500 600 750 --n-z -1 --tv-or-lasso-mode cvxpy-constrEq-reweight1 --reproducible reproducible --measurement-type gaussian --noise-std 0.0 0.1 0.5 --dataset mnist fashion-mnist celebA


#DEPRECATED
#for dim in 5 10 20 40 60 100; do python ./src/execute_setting.py --submit-mode qsub --model-types 'vae-flex' --init-mode "previous-and-random"  --grid "$dim" --flex-chosen $dim --num-measurements 25 --pretrained-model-dir './mnist_vae/models/' --qsub-time 200000 --measurement-type gaussian --reproducible load_standard --noise-std 0.0 --tol 1 --input-type random-test --input-seed 2019 --fair-counter 7; done #eps irrelevant
#for dim in 5 10 20 40 60 100; do python ./src/execute_setting.py --submit-mode qsub --model-types 'vae-flex' --init-mode "previous-and-random"  --grid "$dim" --flex-chosen $dim --num-measurements 10 --pretrained-model-dir './mnist_vae/models/' --qsub-time 50000 --measurement-type gaussian --reproducible load_standard --noise-std 0.0 --tol 1 --input-type random-test --input-seed 2019 --fair-counter 2; done:
    
for dim in 5 10 20 40 60 100; do python ./src/execute_setting.py --submit-mode qsub --model-types 'vae-flex' --init-mode "previous-and-random"  --grid "$dim" --flex-chosen $dim --num-measurements 25 --pretrained-model-dir './mnist_vae/models/' --qsub-time 200000 --measurement-type gaussian --reproducible load_standard --noise-std 0.0 --tol 1 --input-type random-test --input-seed 2019 --fair-counter-end 7; done #eps irrelevant    
for dim in 5 10 20 40 60 100; do python ./src/execute_setting.py --submit-mode qsub --model-types 'vae-flex' --init-mode "previous-and-random"  --grid "$dim" --flex-chosen $dim --num-measurements 10 25 50 100 200 750 --pretrained-model-dir './mnist_vae/models/' --qsub-time 50000 --measurement-type gaussian --reproducible reproducible --noise-std 0.0 --tol 1 --input-type random-test --input-seed 2019 --fair-counter 'unequal' --fair-counter-end 1; done    

#
#python ./src/execute_setting.py --submit-mode qsub --model-types lasso-wavelet --init-mode "previous-and-random"  --num-measurements 100  --n-z -1 --tv-or-lasso-mode bestkTermApprox-constrEq-reweight1-synthesis-kterm5-nonredundant-28 --reproducible reproducible --measurement-type project
#python ./src/execute_setting.py --submit-mode qsub --model-types lasso-wavelet --init-mode "previous-and-random"  --num-measurements 100  --n-z -1 --tv-or-lasso-mode bestkTermApprox-constrEq-reweight1-synthesis-kterm10-nonredundant-28 --reproducible reproducible --measurement-type project
#python ./src/execute_setting.py --submit-mode qsub --model-types lasso-wavelet --init-mode "previous-and-random"  --num-measurements 100  --n-z -1 --tv-or-lasso-mode bestkTermApprox-constrEq-reweight1-synthesis-kterm20-nonredundant-28 --reproducible reproducible --measurement-type project
#python ./src/execute_setting.py --submit-mode qsub --model-types lasso-wavelet --init-mode "previous-and-random"  --num-measurements 100  --n-z -1 --tv-or-lasso-mode bestkTermApprox-constrEq-reweight1-synthesis-kterm40-nonredundant-28 --reproducible reproducible --measurement-type project
#python ./src/execute_setting.py --submit-mode qsub --model-types lasso-wavelet --init-mode "previous-and-random"  --num-measurements 100  --n-z -1 --tv-or-lasso-mode bestkTermApprox-constrEq-reweight1-synthesis-kterm60-nonredundant-28 --reproducible reproducible --measurement-type project
#python ./src/execute_setting.py --submit-mode qsub --model-types lasso-wavelet --init-mode "previous-and-random"  --num-measurements 100  --n-z -1 --tv-or-lasso-mode bestkTermApprox-constrEq-reweight1-synthesis-kterm80-nonredundant-28 --reproducible reproducible --measurement-type project
#python ./src/execute_setting.py --submit-mode qsub --model-types lasso-wavelet --init-mode "previous-and-random"  --num-measurements 100  --n-z -1 --tv-or-lasso-mode bestkTermApprox-constrEq-reweight1-synthesis-kterm100-nonredundant-28 --reproducible reproducible --measurement-type project
#python ./src/execute_setting.py --submit-mode qsub --model-types lasso-wavelet --init-mode "previous-and-random"  --num-measurements 100  --n-z -1 --tv-or-lasso-mode bestkTermApprox-constrEq-reweight1-synthesis-kterm125-nonredundant-28 --reproducible reproducible --measurement-type project
#python ./src/execute_setting.py --submit-mode qsub --model-types lasso-wavelet --init-mode "previous-and-random"  --num-measurements 100  --n-z -1 --tv-or-lasso-mode bestkTermApprox-constrEq-reweight1-synthesis-kterm150-nonredundant-28 --reproducible reproducible --measurement-type project
#python ./src/execute_setting.py --submit-mode qsub --model-types lasso-wavelet --init-mode "previous-and-random"  --num-measurements 100  --n-z -1 --tv-or-lasso-mode bestkTermApprox-constrEq-reweight1-synthesis-kterm175-nonredundant-28 --reproducible reproducible --measurement-type project
#python ./src/execute_setting.py --submit-mode qsub --model-types lasso-wavelet --init-mode "previous-and-random"  --num-measurements 100  --n-z -1 --tv-or-lasso-mode bestkTermApprox-constrEq-reweight1-synthesis-kterm200-nonredundant-28 --reproducible reproducible --measurement-type project
#python ./src/execute_setting.py --submit-mode qsub --model-types lasso-wavelet --init-mode "previous-and-random"  --num-measurements 100  --n-z -1 --tv-or-lasso-mode bestkTermApprox-constrEq-reweight1-synthesis-kterm250-nonredundant-28 --reproducible reproducible --measurement-type project
#python ./src/execute_setting.py --submit-mode qsub --model-types lasso-wavelet --init-mode "previous-and-random"  --num-measurements 100  --n-z -1 --tv-or-lasso-mode bestkTermApprox-constrEq-reweight1-synthesis-kterm275-nonredundant-28 --reproducible reproducible --measurement-type project
#python ./src/execute_setting.py --submit-mode qsub --model-types lasso-wavelet --init-mode "previous-and-random"  --num-measurements 100  --n-z -1 --tv-or-lasso-mode bestkTermApprox-constrEq-reweight1-synthesis-kterm300-nonredundant-28 --reproducible reproducible --measurement-type project
#python ./src/execute_setting.py --submit-mode qsub --model-types lasso-wavelet --init-mode "previous-and-random"  --num-measurements 100  --n-z -1 --tv-or-lasso-mode bestkTermApprox-constrEq-reweight1-synthesis-kterm350-nonredundant-28 --reproducible reproducible --measurement-type project
#python ./src/execute_setting.py --submit-mode qsub --model-types lasso-wavelet --init-mode "previous-and-random"  --num-measurements 100  --n-z -1 --tv-or-lasso-mode bestkTermApprox-constrEq-reweight1-synthesis-kterm400-nonredundant-28 --reproducible reproducible --measurement-type project
#python ./src/execute_setting.py --submit-mode qsub --model-types lasso-wavelet --init-mode "previous-and-random"  --num-measurements 100  --n-z -1 --tv-or-lasso-mode bestkTermApprox-constrEq-reweight1-synthesis-kterm450-nonredundant-28 --reproducible reproducible --measurement-type project
#python ./src/execute_setting.py --submit-mode qsub --model-types lasso-wavelet --init-mode "previous-and-random"  --num-measurements 100  --n-z -1 --tv-or-lasso-mode bestkTermApprox-constrEq-reweight1-synthesis-kterm500-nonredundant-28 --reproducible reproducible --measurement-type project
#python ./src/execute_setting.py --submit-mode qsub --model-types lasso-wavelet --init-mode "previous-and-random"  --num-measurements 100  --n-z -1 --tv-or-lasso-mode bestkTermApprox-constrEq-reweight1-synthesis-kterm550-nonredundant-28 --reproducible reproducible --measurement-type project
#python ./src/execute_setting.py --submit-mode qsub --model-types lasso-wavelet --init-mode "previous-and-random"  --num-measurements 100  --n-z -1 --tv-or-lasso-mode bestkTermApprox-constrEq-reweight1-synthesis-kterm600-nonredundant-28 --reproducible reproducible --measurement-type project
#python ./src/execute_setting.py --submit-mode qsub --model-types lasso-wavelet --init-mode "previous-and-random"  --num-measurements 100  --n-z -1 --tv-or-lasso-mode bestkTermApprox-constrEq-reweight1-synthesis-kterm650-nonredundant-28 --reproducible reproducible --measurement-type project
#python ./src/execute_setting.py --submit-mode qsub --model-types lasso-wavelet --init-mode "previous-and-random"  --num-measurements 100  --n-z -1 --tv-or-lasso-mode bestkTermApprox-constrEq-reweight1-synthesis-kterm700-nonredundant-28 --reproducible reproducible --measurement-type project
#python ./src/execute_setting.py --submit-mode qsub --model-types lasso-wavelet --init-mode "previous-and-random"  --num-measurements 100  --n-z -1 --tv-or-lasso-mode bestkTermApprox-constrEq-reweight1-synthesis-kterm750-nonredundant-28 --reproducible reproducible --measurement-type project
#python ./src/execute_setting.py --submit-mode qsub --model-types lasso-wavelet --init-mode "previous-and-random"  --num-measurements 100  --n-z -1 --tv-or-lasso-mode bestkTermApprox-constrEq-reweight1-synthesis-kterm784-nonredundant-28 --reproducible reproducible --measurement-type project

